'use client';

import { useEffect, useState } from 'react';
import './live-history.css';

type Summary = { fixtureId:string; providerFixtureId:string|null; home:string; away:string; kickoffUtc:string|null; snapshotCount:number; firstSnapshotMinute:number|null; lastSnapshotMinute:number|null; actualHtObserved:boolean; latestStatus:string|null; latestHomeScore:number|null; latestAwayScore:number|null; signalCount:number; status:'finished'|'incomplete'; identity?:'resolved'|'raw_only' };
type Checkpoint = { target:number|'HT'; actualMinute:number|null; status:string|null; insufficient:boolean; homeScore:number|null; awayScore:number|null; dangerousAttacksHome:number|null; dangerousAttacksAway:number|null; attacksHome:number|null; attacksAway:number|null; shotsHome:number|null; shotsAway:number|null; shotsOnTargetHome:number|null; shotsOnTargetAway:number|null; cornersHome:number|null; cornersAway:number|null; possessionHome:number|null; possessionAway:number|null };
type Signal = { id:string; ruleId:string; ruleVersion:string; signalSide:string|null; triggeredAt:string; detectedMinute:number|null; ruleParameters:Record<string,unknown>|null; feature:Record<string,unknown>|null };
type Detail = { fixture:Pick<Summary,'fixtureId'|'providerFixtureId'|'home'|'away'|'kickoffUtc'>; status:'finished'|'incomplete'; latest:{capturedAt:string;status:string|null;elapsedMinute:number|null;homeScore:number|null;awayScore:number|null}|null; snapshotCount:number; firstSnapshotMinute:number|null;lastSnapshotMinute:number|null;actualHtObserved:boolean;maxGapSeconds:number|null;checkpoints:Checkpoint[];signals:Signal[];identity?:'resolved'|'raw_only' };

const value = (number:number|null|undefined) => number === null || number === undefined ? '—' : String(number);
const minute = (number:number|null) => number === null ? '—' : `${number}'`;
const time = (iso:string|null) => iso ? new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(iso))+' JST' : '—';

export default function LiveHistoryPage() {
  const [fixtures,setFixtures]=useState<Summary[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{fetch('/api/live-history?limit=50',{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error??'LIVE履歴の取得に失敗しました');setFixtures(data.fixtures??[])}).catch(e=>setError(e instanceof Error?e.message:'LIVE履歴の取得に失敗しました')).finally(()=>setLoading(false))},[]);
  async function open(fixtureId:string){setError('');setSelected(null);try{const response=await fetch(`/api/live-history?fixtureId=${encodeURIComponent(fixtureId)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error??'履歴詳細の取得に失敗しました');setSelected(data.detail)}catch(e){setError(e instanceof Error?e.message:'履歴詳細の取得に失敗しました')}}
  return <main className="live-history-shell"><header className="live-history-topbar"><div><span>GOAL LIVE</span><strong>LIVE履歴</strong><small>D1に保存された監視結果</small></div><a href="/">← LIVE監視へ戻る</a></header><section className="live-history-intro"><h1>完了試合・途中終了試合を、保存済みデータから確認</h1><p>Collectorの現在メモリではなく、D1のlive_snapshots / live_signalsを読取専用で表示します。identity未解決のRAW-only試合も確認できます。</p></section>{error&&<p className="live-history-error">{error}</p>}<section className="live-history-layout"><div className="history-list"><div className="history-list-head"><b>監視履歴</b><span>{loading?'読込中…':`${fixtures.length} fixtures`}</span></div>{fixtures.map(fixture=><button className="history-row" key={fixture.fixtureId} onClick={()=>void open(fixture.fixtureId)}><div><strong>{fixture.home} <em>{value(fixture.latestHomeScore)}–{value(fixture.latestAwayScore)}</em> {fixture.away}</strong><small>{time(fixture.kickoffUtc)} · {fixture.status==='finished'?'Finished':'incomplete'}{fixture.identity==='raw_only'?' · RAW-only':''}</small></div><div className="history-row-meta"><span>{fixture.identity==='raw_only'?'RAW events':'Snapshots'} {fixture.snapshotCount}</span><span>Start {minute(fixture.firstSnapshotMinute)} · Last {minute(fixture.lastSnapshotMinute)}</span><span>HT {fixture.actualHtObserved?'✓':'未取得'} · Signals {fixture.signalCount}</span></div></button>)}{!loading&&!fixtures.length&&<p className="live-history-empty">保存済みLIVE snapshotはまだありません。</p>}</div><div className="history-detail">{selected?<HistoryDetail detail={selected}/>:<div className="live-history-empty"><b>試合を選択してください</b><p>保存済みcheckpoint・HT baseline・signalを確認できます。</p></div>}</div></section></main>;
}

function HistoryDetail({detail}:{detail:Detail}) { return <><div className="history-detail-head"><span>{detail.status==='finished'?'FINISHED':'INCOMPLETE'}{detail.identity==='raw_only'?' · RAW-ONLY':''}</span><h2>{detail.fixture.home} <b>{value(detail.latest?.homeScore)}–{value(detail.latest?.awayScore)}</b> {detail.fixture.away}</h2><small>{time(detail.fixture.kickoffUtc)} · {detail.identity==='raw_only'?'core fixture: 未解決（RAWを読取表示）':`core fixture: ${detail.fixture.fixtureId}`} · GOAL fixture: {detail.fixture.providerFixtureId??'—'}</small><p>{detail.identity==='raw_only'?'RAW events':'Snapshots'} {detail.snapshotCount} · Start {minute(detail.firstSnapshotMinute)} · Last {minute(detail.lastSnapshotMinute)} · HT baseline {detail.actualHtObserved?'✓':'未取得'}{detail.maxGapSeconds!==null?` · Max gap ${Math.round(detail.maxGapSeconds)} sec`:''}</p></div><section className="checkpoint-section"><h3>CAUSAL CHECKPOINTS <small>future snapshotは使用しません</small></h3><div className="checkpoint-scroll"><table><thead><tr><th>checkpoint</th><th>score</th><th>DA</th><th>attacks</th><th>shots</th><th>SOT</th><th>corners</th><th>possession</th></tr></thead><tbody>{detail.checkpoints.map(checkpoint=><tr key={String(checkpoint.target)} className={checkpoint.insufficient?'missing':''}><th>{checkpoint.target==='HT'?'actual HT':`${checkpoint.target}'`}<small>{checkpoint.insufficient?'未取得':checkpoint.actualMinute===checkpoint.target?'exact':`${checkpoint.actualMinute}'`}</small></th><td>{value(checkpoint.homeScore)} – {value(checkpoint.awayScore)}</td><td>{value(checkpoint.dangerousAttacksHome)} – {value(checkpoint.dangerousAttacksAway)}</td><td>{value(checkpoint.attacksHome)} – {value(checkpoint.attacksAway)}</td><td>{value(checkpoint.shotsHome)} – {value(checkpoint.shotsAway)}</td><td>{value(checkpoint.shotsOnTargetHome)} – {value(checkpoint.shotsOnTargetAway)}</td><td>{value(checkpoint.cornersHome)} – {value(checkpoint.cornersAway)}</td><td>{value(checkpoint.possessionHome)} – {value(checkpoint.possessionAway)}</td></tr>)}</tbody></table></div></section><section className="signal-section"><h3>DA SIGNALS <small>session filterなし・このfixtureの保存済みsignal</small></h3>{detail.signals.length?detail.signals.map(signal=><article key={signal.id}><b>🔥 {signal.ruleId} / {signal.signalSide??'—'}</b><span>{minute(signal.detectedMinute)} · {time(signal.triggeredAt)}</span><p>HT DA {value(numberFeature(signal.feature,'htHomeDangerousAttacks'))} – {value(numberFeature(signal.feature,'htAwayDangerousAttacks'))} / Current DA {value(numberFeature(signal.feature,'currentHomeDangerousAttacks'))} – {value(numberFeature(signal.feature,'currentAwayDangerousAttacks'))} / Increase {signed(numberFeature(signal.feature,'homeDaIncrease'))} – {signed(numberFeature(signal.feature,'awayDaIncrease'))}</p></article>):<p className="live-history-empty">保存済みDA signalはありません。</p>}</section></> }
function numberFeature(feature:Record<string,unknown>|null,key:string){const value=feature?.[key];return typeof value==='number'&&Number.isFinite(value)?value:null}
function signed(value:number|null){return value===null?'—':`${value>=0?'+':''}${value}`}
