import test from 'node:test'; import assert from 'node:assert/strict';
import { GoalApiCollector } from '../../../services/collector/collector-core.mjs';
class FakeSocket { static instances = []; constructor() { this.readyState = 0; this.listeners = {}; this.sent = []; FakeSocket.instances.push(this); } addEventListener(type, fn) { (this.listeners[type] ??= []).push(fn); } send(value) { this.sent.push(JSON.parse(value)); } close(code = 1000, reason = '') { this.readyState = 3; this.fire('close', { code, reason }); } fire(type, value = {}) { for (const fn of this.listeners[type] ?? []) fn(value); } open() { this.readyState = 1; this.fire('open'); } message(value) { this.fire('message', { data: JSON.stringify(value) }); } }
const fixture = { id: 'fixture-1', home: 'Home', away: 'Away', homeScore: '0', awayScore: '0', status: '1' }; const tick = () => new Promise((resolve) => setTimeout(resolve, 0));
function setup() { FakeSocket.instances = []; const events = [], scheduled = []; const collector = new GoalApiCollector({ apiKey: 'test-key', WebSocketImpl: FakeSocket, fetchImpl: async () => ({ ok: true, json: async () => ({ data: { token: 'secret-token' } }) }), persist: async (event) => events.push(event), schedule: (fn) => { scheduled.push(fn); return fn; }, cancelSchedule: () => {} }); return { collector, events, scheduled }; }
test('one socket subscribes multiple selected fixtures', async () => { const { collector } = setup(); await collector.start([fixture, { ...fixture, id: 'fixture-2' }]); await tick(); const socket = FakeSocket.instances[0]; socket.open(); socket.message({ type: 'auth_success', data: {} }); await tick(); assert.deepEqual(socket.sent.filter((item) => item.type === 'subscribe').map((item) => item.matchId), ['fixture-1', 'fixture-2']); });
test('abnormal disconnect reconnects and re-subscribes', async () => { const { collector, events, scheduled } = setup(); await collector.start([fixture]); await tick(); const first = FakeSocket.instances[0]; first.open(); first.message({ type: 'auth_success' }); await tick(); first.fire('close', { code: 1006, reason: 'network' }); await tick(); assert.equal(scheduled.length, 1); scheduled[0](); await tick(); const second = FakeSocket.instances[1]; second.open(); second.message({ type: 'auth_success' }); await tick(); assert.equal(second.sent.some((item) => item.type === 'subscribe' && item.matchId === 'fixture-1'), true); assert.equal(events.some((event) => event.eventType === 'socket_disconnect'), true); assert.equal(events.some((event) => event.eventType === 'reconnect_scheduled'), true); assert.equal(events.some((event) => event.eventType === 'resubscribe'), true); });
test('manual stop never schedules reconnect', async () => { const { collector, scheduled, events } = setup(); await collector.start([fixture]); await tick(); const socket = FakeSocket.instances[0]; socket.open(); socket.message({ type: 'auth_success' }); await tick(); await collector.stop('manual_stop'); await tick(); assert.equal(scheduled.length, 0); assert.equal(events.some((event) => event.eventType === 'session_stop'), true); });
test('raw match update remains intact and duplicate stats survive', async () => { const { collector, events } = setup(); await collector.start([fixture]); await tick(); const socket = FakeSocket.instances[0]; socket.open(); socket.message({ type: 'auth_success' }); const raw = { type: 'match_update', data: { id: 'fixture-1', match_status: '60', match_hometeam_score: '1', match_awayteam_score: '0', statistics: [{ type: 'Corners', home: '1', away: '2' }, { type: 'Corners', home: '3', away: '2' }], cards: [], substitutions: {} } }; socket.message(raw); await tick(); const stored = events.find((event) => event.eventType === 'match_update'); assert.deepEqual(stored.payload, raw); assert.equal(collector.status().fixtures[0].status, '60'); assert.equal(collector.status().fixtures[0].stats.length, 2); });
test('terminal update finalizes fixture and session', async () => { const { collector, events, scheduled } = setup(); await collector.start([fixture]); await tick(); const socket = FakeSocket.instances[0]; socket.open(); socket.message({ type: 'auth_success' }); socket.message({ type: 'match_update', data: { id: 'fixture-1', match_status: 'FT', match_live: '0', match_hometeam_score: '2', match_awayteam_score: '1', statistics: [] } }); await tick(); assert.equal(collector.status().active, false); assert.equal(events.some((event) => event.eventType === 'fixture_end'), true); assert.equal(events.some((event) => event.eventType === 'session_stop'), true); assert.equal(scheduled.length, 0); });
