import test from 'node:test'; import assert from 'node:assert/strict';
import { evaluateDangerousAttacksHtIncrease, evaluateDangerousAttacksKickoffIncrease } from '../lib/dangerous-attacks-signal.ts';

const ht = (home = 38, away = 29) => ({ fixtureId:'goal-api:f',provider:'goal-api',providerFixtureId:'f',sourceClientEventId:'ht-event',providerEventKey:'ht-hash',capturedAt:'2026-09-13T10:00:00.000Z',elapsedMinute:45,addedTime:null,matchStatus:'Half Time',homeScore:0,awayScore:0,dangerousAttacksHome:home,dangerousAttacksAway:away });
const current = ({ minute=58, home=54, away=35, at='2026-09-13T10:13:00.000Z' }={}) => ({ fixtureId:'goal-api:f',provider:'goal-api',providerFixtureId:'f',sourceClientEventId:`event-${minute}`,providerEventKey:`hash-${minute}`,capturedAt:at,elapsedMinute:minute,addedTime:null,matchStatus:String(minute),homeScore:0,awayScore:0,dangerousAttacksHome:home,dangerousAttacksAway:away });
const run = (baseline=ht(), now=current(), identityResolved=true) => evaluateDangerousAttacksHtIncrease({ baseline, current:now, identityResolved });

test('HOME +16 at 58 creates one reproducible DA signal', () => { const result=run(); assert.equal(result.kind,'eligible'); assert.deepEqual(result.signals.map(x=>x.side),['HOME']); assert.equal(result.signals[0].feature.homeDaIncrease,16); assert.equal(result.signals[0].feature.minutesSinceHt,13); assert.equal(result.signals[0].feature.baselineSnapshotId,'ht-event'); assert.equal(result.signals[0].feature.triggerSnapshotId,'event-58'); });
test('HOME +14 does not fire', () => { const result=run(ht(),current({home:52})); assert.equal(result.kind,'eligible'); assert.equal(result.signals.length,0); });
test('deadline is inclusive at 65 and exclusive at 66', () => { assert.deepEqual(run(ht(),current({minute:64,home:53})).signals.map(x=>x.side),['HOME']); assert.deepEqual(run(ht(),current({minute:65,home:53})).signals.map(x=>x.side),['HOME']); const after=run(ht(),current({minute:66,home:53})); assert.equal(after.kind,'not_applicable'); assert.equal(after.reason,'deadline_passed'); });
test('AWAY evaluates independently', () => { const result=run(ht(),current({home:40,away:44})); assert.equal(result.kind,'eligible'); assert.deepEqual(result.signals.map(x=>x.side),['AWAY']); assert.equal(result.signals[0].feature.awayDaIncrease,15); });
test('same side uses one deterministic signal identity across subsequent updates', () => { const first=run(ht(),current({minute:58,home:54})).signals[0]; const next=run(ht(),current({minute:60,home:58})).signals[0]; assert.equal(first.signalId,next.signalId); assert.equal(first.signalKey,'HOME'); });
test('missing baseline, null DA, unresolved identity and provider correction never fire', () => { assert.deepEqual(run(null,current()),{kind:'not_applicable',reason:'ht_baseline_missing'}); assert.deepEqual(run(ht(),current({home:null})),{kind:'not_applicable',reason:'current_dangerous_attacks_missing'}); assert.deepEqual(run(ht(),current(),false),{kind:'not_applicable',reason:'fixture_identity_unresolved'}); assert.deepEqual(run(ht(),current({home:37})),{kind:'quality_skip',reason:'dangerous_attacks_cumulative_decrease'}); });
test('a future HT baseline is rejected to prevent look-ahead', () => { const future={...ht(),capturedAt:'2026-09-13T10:14:00.000Z'}; assert.deepEqual(run(future,current()),{kind:'quality_skip',reason:'future_ht_baseline_rejected'}); });

const kickoff = (home = 0, away = 0) => ({ ...ht(home, away), sourceClientEventId:'ko-event', providerEventKey:'ko-hash', capturedAt:'2026-09-13T09:00:00.000Z', elapsedMinute:0, matchStatus:'0' });
const early = ({ minute=20, home=20, away=0, at='2026-09-13T09:20:00.000Z' }={}) => ({ ...current({ minute, home, away, at }), sourceClientEventId:`early-${minute}`, providerEventKey:`early-hash-${minute}` });
const runKickoff = (baseline=kickoff(), now=early(), identityResolved=true) => evaluateDangerousAttacksKickoffIncrease({ baseline, current:now, identityResolved });

test('KO→25 HOME +20 fires independently without changing the HT rule', () => { const result=runKickoff(); assert.equal(result.kind,'eligible'); assert.deepEqual(result.signals.map(x=>x.side),['HOME']); assert.equal(result.signals[0].feature.homeDaIncrease,20); assert.equal(result.signals[0].feature.minutesSinceKickoff,20); assert.equal(result.signals[0].feature.baselineSnapshotId,'ko-event'); });
test('KO threshold is inclusive at 25 and no new signal fires at 26', () => { assert.deepEqual(runKickoff(kickoff(),early({minute:25,home:20})).signals.map(x=>x.side),['HOME']); const after=runKickoff(kickoff(),early({minute:26,home:25})); assert.equal(after.kind,'not_applicable'); assert.equal(after.reason,'deadline_passed'); });
test('KO +19, missing kickoff, post-kickoff baseline and corrections never fire', () => { assert.equal(runKickoff(kickoff(),early({home:19})).signals.length,0); assert.deepEqual(runKickoff(null,early()),{kind:'not_applicable',reason:'kickoff_baseline_missing'}); assert.deepEqual(runKickoff({ ...kickoff(), elapsedMinute:20 },early()),{kind:'quality_skip',reason:'kickoff_baseline_not_observed'}); assert.deepEqual(runKickoff(kickoff(10,0),early({home:9})),{kind:'quality_skip',reason:'dangerous_attacks_cumulative_decrease'}); });
test('KO signal identity is stable across updates and AWAY can fire alone', () => { const first=runKickoff(kickoff(),early({minute:20,home:20})).signals[0]; const later=runKickoff(kickoff(),early({minute:22,home:24})).signals[0]; assert.equal(first.signalId,later.signalId); assert.deepEqual(runKickoff(kickoff(),early({home:2,away:20})).signals.map(x=>x.side),['AWAY']); });
