#!/usr/bin/env node
import fs from 'node:fs'; import http from 'node:http'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { GoalApiCollector } from './collector-core.mjs';
import { BookmarkScheduler } from './bookmark-scheduler.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const PORT = Number(process.env.GOAL_COLLECTOR_PORT ?? 4317); const DASHBOARD_URL = process.env.GOAL_DASHBOARD_URL ?? 'http://localhost:3000';
for (const raw of fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/)) { const line = raw.trim(); if (!line || line.startsWith('#') || !line.includes('=')) continue; const index = line.indexOf('='); const key = line.slice(0, index).trim(); let value = line.slice(index + 1).trim(); if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1); if (!(key in process.env)) process.env[key] = value; }
let sessionDirectory = null; const queue = []; let flushing = false; let persistenceRetryAttempt = 0; let persistenceRetryTimer = null;
const TERMINAL_FIXTURE_STATUSES = new Set(['FT', 'FINISHED', 'AFTER_ET', 'AFTER_PEN', 'CANCELLED', 'ABANDONED', 'AWARDED']);
async function persist(event) { if (!sessionDirectory) { sessionDirectory = path.join(ROOT, 'data/goal_api_test/collector', event.sessionId.replace(/[^a-zA-Z0-9_.-]/g, '_')); fs.mkdirSync(sessionDirectory, { recursive: true }); } fs.appendFileSync(path.join(sessionDirectory, 'events.jsonl'), `${JSON.stringify(event)}\n`, 'utf8'); queue.push(event); void flush(); const terminalUpdate = event.eventType === 'match_update' && TERMINAL_FIXTURE_STATUSES.has(String(event.status ?? '').toUpperCase()); if (event.eventType === 'match_update' && !terminalUpdate) void updateBookmark(event.fixtureId, 'monitoring'); if (event.eventType === 'fixture_end') void updateBookmark(event.fixtureId, 'finished'); }
async function updateBookmark(fixtureId, status) { try { await fetch(`${DASHBOARD_URL}/api/bookmarks`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ fixtureId, status }), signal:AbortSignal.timeout(10_000) }); } catch {} }
async function flush() { if (flushing || !queue.length || persistenceRetryTimer) return; flushing = true; try { while (queue.length) { const batch = queue.slice(0, 100); const response = await fetch(`${DASHBOARD_URL}/api/monitor-events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ events: batch }), signal: AbortSignal.timeout(10_000) }); const responseText = await response.text(); if (!response.ok) throw new Error(`monitor-events HTTP ${response.status}: ${responseText.slice(0, 200)}`); logSignalProjection(responseText); queue.splice(0, batch.length); persistenceRetryAttempt = 0; } } catch (error) { persistenceRetryAttempt += 1; const delayMs = Math.min(2_000 * 2 ** Math.min(persistenceRetryAttempt - 1, 5), 60_000); process.stderr.write(`collector persistence retry in ${delayMs}ms: ${String(error)}\n`); persistenceRetryTimer = setTimeout(() => { persistenceRetryTimer = null; void flush(); }, delayMs); persistenceRetryTimer.unref?.(); } finally { flushing = false; } }
function logSignalProjection(responseText) { try { const projection = JSON.parse(responseText)?.projection; if (!projection || (!projection.signalSaved && !projection.signalQualitySkipped && !projection.signalErrors)) return; process.stdout.write(`live signal projection: saved=${projection.signalSaved ?? 0} duplicate=${projection.signalDuplicates ?? 0} quality=${projection.signalQualitySkipped ?? 0} error=${projection.signalErrors ?? 0} reasons=${JSON.stringify(projection.signalReasons ?? {})}\n`); } catch {} }
const collector = new GoalApiCollector({ apiKey: process.env.GOAL_API_KEY, persist });
const bookmarkScheduler = new BookmarkScheduler({ collector, dashboardUrl: DASHBOARD_URL });
const server = http.createServer(async (request, response) => { response.setHeader('Content-Type', 'application/json; charset=utf-8'); response.setHeader('Cache-Control', 'no-store'); try { if (request.method === 'GET' && request.url === '/status') return send(response, 200, collector.status()); if (request.method !== 'POST' || request.url !== '/control') return send(response, 404, { error: 'not found' }); const body = await readJson(request); let status; if (body.action === 'start') { sessionDirectory = null; status = await collector.start(body.fixtures); } else if (body.action === 'add') status = await collector.add(body.fixtures); else if (body.action === 'remove') status = await collector.remove(body.fixtureId, body.reason); else if (body.action === 'refresh') status = await collector.refresh(body.fixtureId, body.reason); else if (body.action === 'stop') status = await collector.stop('manual_stop'); else return send(response, 400, { error: 'unknown action' }); return send(response, 200, status); } catch (error) { return send(response, 500, { error: error instanceof Error ? error.message : String(error) }); } });
server.listen(PORT, '127.0.0.1', () => process.stdout.write(`GOAL collector listening on 127.0.0.1:${PORT}\n`));
setInterval(() => void collector.checkHealth(), 30_000).unref();
const bookmarkTimer = setInterval(() => void bookmarkScheduler.tick().catch(() => undefined), 30_000); bookmarkTimer.unref();
setTimeout(() => void bookmarkScheduler.tick().catch(() => undefined), 1_000).unref();
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, async () => { await collector.stop(`daemon_${signal.toLowerCase()}`); server.close(() => process.exit(0)); setTimeout(() => process.exit(0), 1500).unref(); });
function send(response, status, body) { response.statusCode = status; response.end(JSON.stringify(body)); }
function readJson(request) { return new Promise((resolve, reject) => { let raw = ''; request.on('data', (chunk) => { raw += chunk; if (raw.length > 1_000_000) request.destroy(); }); request.on('end', () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch (error) { reject(error); } }); request.on('error', reject); }); }
