import {env} from 'cloudflare:workers';import {ensureRuntimeSchema} from '@/db/schema';import {analysisDownloadFilename,detailForAnalysis,resultFixtureRecords} from '@/lib/result-capture';import {oddsFixtureLookupResponses,oddsUnmatched} from '@/lib/odds-run-payload';export const dynamic='force-dynamic';
type OddsRun={run_id:string;form_run_id:string|null;created_at:string;api_requests:number;matched_fixtures:number;unmatched_json:string;fixtures_json:string};
export async function GET(request:Request){
 const db=(env as unknown as{DB:D1Database}).DB;await ensureRuntimeSchema(db);const wanted=new URL(request.url).searchParams.get('runId');
 const statement=db.prepare(`SELECT run_id,form_run_id,created_at,api_requests,matched_fixtures,unmatched_json,fixtures_json FROM odds_analysis_runs ${wanted?'WHERE run_id=? ':''}ORDER BY created_at DESC LIMIT 1`),run=wanted?await statement.bind(wanted).first<OddsRun>():await statement.first<OddsRun>();if(!run)return Response.json({error:'保存済みオッズ履歴がありません'},{status:404});
 const snapshots=await db.prepare('SELECT api_fixture_id,kickoff,home,away,raw_json FROM odds_snapshots WHERE run_id=? ORDER BY kickoff,id').bind(run.run_id).all();
 const form=run.form_run_id?await db.prepare('SELECT run_id,created_at,checked_teams,failed_teams,api_requests,candidates_json,checked_json FROM form_analysis_runs WHERE run_id=?').bind(run.form_run_id).first<any>():null;
 const result=await db.prepare('SELECT created_at,api_requests,raw_json FROM result_snapshots WHERE odds_run_id=? ORDER BY created_at DESC LIMIT 1').bind(run.run_id).first<any>();
 const resultRaw=result?JSON.parse(result.raw_json):null;const resultFixtures=resultFixtureRecords(resultRaw);const payload={format:'goal-live-analysis-bundle-v3',instructions:['Treat odds and form as pre-match snapshots.','Analyze only information known at the recorded acquisition time.','Use the result snapshot only for settlement.','Test consistent rules across every available market; report sample size, 1-unit profit, ROI, hit rate and overfitting risk.','Do not claim profitability from a small sample.'],exportedAt:new Date().toISOString(),oddsRun:{runId:run.run_id,formRunId:run.form_run_id,createdAt:run.created_at,apiRequests:run.api_requests,matchedFixtures:run.matched_fixtures,unmatched:oddsUnmatched(run.unmatched_json),fixtureLookupResponses:oddsFixtureLookupResponses(run.fixtures_json)},formAnalysis:form?{runId:form.run_id,createdAt:form.created_at,checkedTeams:form.checked_teams,failedTeams:form.failed_teams,apiRequests:form.api_requests,candidates:JSON.parse(form.candidates_json||'[]'),checkedTeamsData:JSON.parse(form.checked_json||'[]')}:null,oddsSnapshots:(snapshots.results??[]).map((s:any)=>({apiFixtureId:s.api_fixture_id,kickoff:s.kickoff,home:s.home,away:s.away,raw:JSON.parse(s.raw_json)})),resultSnapshot:result?{createdAt:result.created_at,apiRequests:result.api_requests,raw:resultRaw,fixtureDetails:resultFixtures.map(detailForAnalysis)}:null};
 return new Response(JSON.stringify(payload,null,2),{headers:{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="${analysisDownloadFilename()}"`,'Cache-Control':'no-store'}})
}
