export type FixtureContext={id:string;kickoffUtc:string;league:string;country?:string;home:{id:string;name:string};away:{id:string;name:string}};
export type BridgeResult={status:'SAFE_MATCH'|'POSSIBLE_MATCH'|'AMBIGUOUS'|'NO_MATCH';evidence:string[];reason:string};
const text=(value:unknown)=>typeof value==='string'&&value.trim()?value:null;
const n=(value:unknown)=>{const v=text(value);return v?v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,''):null};
export function matchFixturePair(goal:FixtureContext,api:FixtureContext):BridgeResult{
 const evidence:string[]=[];const required:[string,unknown][]=[['goal fixture id',goal?.id],['goal kickoff',goal?.kickoffUtc],['goal league',goal?.league],['goal home name',goal?.home?.name],['goal away name',goal?.away?.name],['API-Football fixture id',api?.id],['API-Football kickoff',api?.kickoffUtc],['API-Football league',api?.league],['API-Football home name',api?.home?.name],['API-Football away name',api?.away?.name]];const missing=required.filter(([,value])=>!text(value)).map(([name])=>name);if(missing.length)return{status:'NO_MATCH',evidence,reason:`insufficient_context: ${missing.join(', ')}`};
 const diff=Math.abs(Date.parse(goal.kickoffUtc)-Date.parse(api.kickoffUtc));if(!Number.isFinite(diff))return{status:'NO_MATCH',evidence,reason:'invalid kickoff'};
 if(diff>5*60_000)return{status:'NO_MATCH',evidence,reason:'kickoff differs by over five minutes'};evidence.push(diff===0?'kickoff exact':'kickoff within five minutes');
 const home=n(goal.home.name)===n(api.home.name),away=n(goal.away.name)===n(api.away.name);if(!home||!away)return{status:'NO_MATCH',evidence,reason:'home/away pair differs'};evidence.push('home pair','away pair','orientation');
 if(n(goal.league)!==n(api.league))return{status:'POSSIBLE_MATCH',evidence,reason:'team pair and kickoff match but league differs'};evidence.push('league');const goalCountry=n(goal.country),apiCountry=n(api.country);if(goalCountry&&apiCountry&&goalCountry!==apiCountry)return{status:'POSSIBLE_MATCH',evidence,reason:'team pair and kickoff match but country differs'};if(goalCountry&&apiCountry)evidence.push('country');return{status:'SAFE_MATCH',evidence,reason:'independent fixture evidence agrees'};
}
